#!/usr/bin/env bash

connected=" 󰓅 "
disconnected=" 󰾆 "

CMD="warp-cli status"
while true; do
    $CMD | grep -q "Disconnected" &> /dev/null;
    if [ $? == 0 ]; then
        echo "     Warp Disconnected "

    else
        echo "     Warp Connnected"
    fi

    sleep 0.5
done
