#!/usr/bin/env bash

connected=" 󰓅 "
disconnected=" 󰾆 "

CMD="warp-cli status"
$CMD | grep -q "Disconnected" &> /dev/null;
if [ $? == 0 ]; then
    echo "   Warp Disconnected "

else
    echo "   Warp Connnected"
fi

