require("lr.remap")
require("lr.plugins")
require("lr.lsp")
require("lr.autocmds")
require("lr.dap")
require("lr.completion")
require("lr.options")
require("lr.statusline")
require("lr.git")
require("lr.lspsaga")
require("lr.color-scheme")
require("lr.telescope")
require("lr.treesitter")
-- require("lr.transparent")
require("lr.comment")
