-- This should be prioritized
require("lr.options")

require("lr.color-scheme")
require("lr.keymaps")
require("lr.plugins")
require("lr.autocmds")
require("lr.dap")
require("lr.statusline")
require("lr.git")
require("lr.telescope")
require("lr.treesitter")
require("lr.transparent")
require("lr.comment")
require("lr.ufo")
require("lr.listchars")
require("lr.lsp")
require("lr.completion")
require("lr.lspsaga")
require("lr.copilot")
