--local null_ls_status_ok, null_ls = pcall(require, "null-ls")
--local eslint_status_ok, eslint = pcall(require, "eslint")
--if not null_ls_status_ok or not eslint_status_ok then
--  return
--end
--
--local formatting = null_ls.builtins.formatting
--
--local diagnostics = null_ls.builtins.diagnostics
--
--null_ls.setup {
--}
--
--eslint.setup({
-- bin = 'eslint', -- or `eslint_d`
--  code_actions = {
--    enable = true,
--    apply_on_save = {
--      enable = true,
--      types = { "problem" }, -- "directive", "problem", "suggestion", "layout"
--    },
--    disable_rule_comment = {
--      enable = true,
--      location = "separate_line", -- or `same_line`
--    },
--  },
--  diagnostics = {
--    enable = true,
--    report_unused_disable_directives = false,
--    run_on = "type", -- or `save`
--  },
--})
